-- begin MYERP_PURCHASE_PRODUCT
alter table MYERP_PURCHASE_PRODUCT add constraint FK_MYERP_PURCHASE_PRODUCT_ON_PRODUCT foreign key (PRODUCT_ID) references MYERP_PRODUCT(ID)^
alter table MYERP_PURCHASE_PRODUCT add constraint FK_MYERP_PURCHASE_PRODUCT_ON_PURCHASE foreign key (PURCHASE_ID) references MYERP_PURCHASE(ID)^
create index IDX_MYERP_PURCHASE_PRODUCT_ON_PRODUCT on MYERP_PURCHASE_PRODUCT (PRODUCT_ID)^
create index IDX_MYERP_PURCHASE_PRODUCT_ON_PURCHASE on MYERP_PURCHASE_PRODUCT (PURCHASE_ID)^
-- end MYERP_PURCHASE_PRODUCT
-- begin MYERP_STORE
alter table MYERP_STORE add constraint FK_MYERP_STORE_ON_COMMERCIAL_NETWORK foreign key (COMMERCIAL_NETWORK_ID) references MYERP_COMMERCIAL_NETWORK(ID)^
create unique index IDX_MYERP_STORE_UK_NUMBER_ on MYERP_STORE (NUMBER_) where DELETE_TS is null ^
create index IDX_MYERP_STORE_ON_COMMERCIAL_NETWORK on MYERP_STORE (COMMERCIAL_NETWORK_ID)^
-- end MYERP_STORE
-- begin MYERP_PURCHASE
alter table MYERP_PURCHASE add constraint FK_MYERP_PURCHASE_ON_STORE foreign key (STORE_ID) references MYERP_STORE(ID)^
create index IDX_MYERP_PURCHASE_ON_STORE on MYERP_PURCHASE (STORE_ID)^
-- end MYERP_PURCHASE
-- begin MYERP_MANUFACTURER
alter table MYERP_MANUFACTURER add constraint FK_MYERP_MANUFACTURER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create unique index IDX_MYERP_MANUFACTURER_UK_NAME on MYERP_MANUFACTURER (NAME) where DELETE_TS is null ^
create index IDX_MYERP_MANUFACTURER_ON_USER on MYERP_MANUFACTURER (USER_ID)^
-- end MYERP_MANUFACTURER
-- begin MYERP_COMMERCIAL_NETWORK
create unique index IDX_MYERP_COMMERCIAL_NETWORK_UK_NAME on MYERP_COMMERCIAL_NETWORK (NAME) where DELETE_TS is null ^
-- end MYERP_COMMERCIAL_NETWORK
-- begin MYERP_PRICE_HISTORY
alter table MYERP_PRICE_HISTORY add constraint FK_MYERP_PRICE_HISTORY_ON_PRODUCT foreign key (PRODUCT_ID) references MYERP_PRODUCT(ID)^
alter table MYERP_PRICE_HISTORY add constraint FK_MYERP_PRICE_HISTORY_ON_STORE foreign key (STORE_ID) references MYERP_STORE(ID)^
create index IDX_MYERP_PRICE_HISTORY_ON_PRODUCT on MYERP_PRICE_HISTORY (PRODUCT_ID)^
create index IDX_MYERP_PRICE_HISTORY_ON_STORE on MYERP_PRICE_HISTORY (STORE_ID)^
-- end MYERP_PRICE_HISTORY
-- begin MYERP_PRODUCT
alter table MYERP_PRODUCT add constraint FK_MYERP_PRODUCT_ON_MANUFACTURER foreign key (MANUFACTURER_ID) references MYERP_MANUFACTURER(ID)^
create unique index IDX_MYERP_PRODUCT_UK_NAME on MYERP_PRODUCT (NAME) where DELETE_TS is null ^
create index IDX_MYERP_PRODUCT_ON_MANUFACTURER on MYERP_PRODUCT (MANUFACTURER_ID)^
-- end MYERP_PRODUCT
-- begin MYERP_STORE_PRODUCT
alter table MYERP_STORE_PRODUCT add constraint FK_MYERP_STORE_PRODUCT_ON_STORE foreign key (STORE_ID) references MYERP_STORE(ID)^
alter table MYERP_STORE_PRODUCT add constraint FK_MYERP_STORE_PRODUCT_ON_PRODUCT foreign key (PRODUCT_ID) references MYERP_PRODUCT(ID)^
create index IDX_MYERP_STORE_PRODUCT_ON_STORE on MYERP_STORE_PRODUCT (STORE_ID)^
create index IDX_MYERP_STORE_PRODUCT_ON_PRODUCT on MYERP_STORE_PRODUCT (PRODUCT_ID)^
-- end MYERP_STORE_PRODUCT
