alter table MYERP_STORE_PRODUCT add constraint FK_MYERP_STORE_PRODUCT_ON_STORE foreign key (STORE_ID) references MYERP_STORE(ID);
alter table MYERP_STORE_PRODUCT add constraint FK_MYERP_STORE_PRODUCT_ON_PRODUCT foreign key (PRODUCT_ID) references MYERP_PRODUCT(ID);
create index IDX_MYERP_STORE_PRODUCT_ON_STORE on MYERP_STORE_PRODUCT (STORE_ID);
create index IDX_MYERP_STORE_PRODUCT_ON_PRODUCT on MYERP_STORE_PRODUCT (PRODUCT_ID);
