alter table MYERP_PRICE_HISTORY add constraint FK_MYERP_PRICE_HISTORY_ON_PRODUCT foreign key (PRODUCT_ID) references MYERP_PRODUCT(ID);
alter table MYERP_PRICE_HISTORY add constraint FK_MYERP_PRICE_HISTORY_ON_STORE foreign key (STORE_ID) references MYERP_STORE(ID);
create index IDX_MYERP_PRICE_HISTORY_ON_PRODUCT on MYERP_PRICE_HISTORY (PRODUCT_ID);
create index IDX_MYERP_PRICE_HISTORY_ON_STORE on MYERP_PRICE_HISTORY (STORE_ID);
