alter table MYERP_PURCHASE_PRODUCT add constraint FK_MYERP_PURCHASE_PRODUCT_ON_PRODUCT foreign key (PRODUCT_ID) references MYERP_PRODUCT(ID);
alter table MYERP_PURCHASE_PRODUCT add constraint FK_MYERP_PURCHASE_PRODUCT_ON_PURCHASE foreign key (PURCHASE_ID) references MYERP_PURCHASE(ID);
create index IDX_MYERP_PURCHASE_PRODUCT_ON_PRODUCT on MYERP_PURCHASE_PRODUCT (PRODUCT_ID);
create index IDX_MYERP_PURCHASE_PRODUCT_ON_PURCHASE on MYERP_PURCHASE_PRODUCT (PURCHASE_ID);
