alter table MYERP_PRODUCT add constraint FK_MYERP_PRODUCT_ON_MANUFACTURER foreign key (MANUFACTURER_ID) references MYERP_MANUFACTURER(ID);
create unique index IDX_MYERP_PRODUCT_UK_NAME on MYERP_PRODUCT (NAME) where DELETE_TS is null ;
create index IDX_MYERP_PRODUCT_ON_MANUFACTURER on MYERP_PRODUCT (MANUFACTURER_ID);
