alter table MYERP_MANUFACTURER add constraint FK_MYERP_MANUFACTURER_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create unique index IDX_MYERP_MANUFACTURER_UK_NAME on MYERP_MANUFACTURER (NAME) where DELETE_TS is null ;
create index IDX_MYERP_MANUFACTURER_ON_USER on MYERP_MANUFACTURER (USER_ID);
