alter table MYERP_STORE add constraint FK_MYERP_STORE_ON_COMMERCIAL_NETWORK foreign key (COMMERCIAL_NETWORK_ID) references MYERP_COMMERCIAL_NETWORK(ID);
create unique index IDX_MYERP_STORE_UK_NUMBER_ on MYERP_STORE (NUMBER_) where DELETE_TS is null ;
create index IDX_MYERP_STORE_ON_COMMERCIAL_NETWORK on MYERP_STORE (COMMERCIAL_NETWORK_ID);
